### ISSUE TITLE
Ship standard seller examples as a pure-data package (unitysvc-sellers-data)

### ISSUE THREAD

**Issue by bo-unitysvc** [unitysvc/unitysvc-sellers#25]
## Problem

Every seller data repository currently ships its own copies of boilerplate code examples — connectivity tests, usage snippets, README chunks, Jinja2 templates. For newcomers, writing these from scratch is the single biggest friction point when preparing service data.

`unitysvc-services-template` already hosts 15 well-written standard examples (growing). We want sellers to reference those directly instead of copy-pasting into every repo.

### Example — today

```json
"Connectivity test": {
  "category": "connectivity_test",
  "description": "Verify echo relay endpoint is reachable",
  "file_path": "../../docs/connectivity.sh.j2",
  "is_active": true,
  "is_public": false,
  "meta": { "output_contains": "connectivity ok" },
  "mime_type": "bash"
}
```

Two problems, not one:

1. **The file** (`connectivity.sh.j2`) is copy-pasted into every repo.
2. **The record around it** — `category`, `mime_type`, `meta.output_contains`, `is_public` — is hand-written each time and trivially easy to get wrong. Fixing only `file_path` leaves the bigger footgun in place.

## Two classes of data repo

The solution must serve both:

- **Generated repos** (e.g. `unitysvc-services-deepseek`) — drive `template_populate.py` with an iterator of model dicts; `listing.json.j2` + `offering.json.j2` templates render to `.json` via an `update_services.py` script in the repo.
- **Hand-authored repos** — sellers write `listing.json` / `listing.toml` directly, no render step.

A solution that only helps generated repos leaves newcomers — the audience this ticket is for — out in the cold.

## Constraints that shape the design

1. The SDK's existing `file_path` resolver in [upload.py:201](src/unitysvc_sellers/upload.py:201) runs referenced files through `render_template_file()` in [utils.py:213](src/unitysvc_sellers/utils.py:213), rendering Jinja2 with `listing`, `offering`, `provider`, `interface`, and `seller` context. **Per-listing Jinja rendering must stay client-side** (rules out handing a URL to the backend as `external_url`).
2. `upstream_access_config` values and referenced code examples (`.sh.j2`, `.py.j2`) **already contain `{{ }}` Jinja syntax meant for this Pass-2 render**. Any expansion mechanism we introduce at the listing level **must not collide** with those tokens. `{% raw %}` escaping is not an acceptable authoring burden.

## Recommendation — data package + JSON sentinels for presets

Three pieces, each doing one job, with **zero Jinja layered above Pass 2** and **no custom URL scheme**.

### Piece 1 — `unitysvc-sellers-data`: a pure-data PyPI package

Contains raw example files under stable versioned names (`s3-connectivity-v1.sh`, `s3-python-boto3-v1.py.j2`, ...) and preset functions that return full document records with **pre-resolved absolute paths** to the bundled files. Pure data, no runtime deps, installed via pip.

### Piece 2 — `$preset` JSON sentinels, expanded by the SDK at upload time

Sellers write listings as ordinary JSON/TOML. Preset references are **structural sentinels**, not Jinja directives:

```json
{
  "documents": {
    "Connectivity test": { "$preset": "s3_connectivity_v1" },
    "Usage (Python)":    { "$preset": "s3_python_boto3_v1",
                           "$with": { "is_public": false,
                                      "description": "Uploads to our dedicated bucket" } }
  },
  "upstream_access_config": {
    "headers": { "Authorization": "Bearer {{ interface.api_key }}" }
  }
}
```

The SDK walks the *parsed* listing dict and replaces `{"$preset": ...}` nodes with the resolved preset record *before* `_resolve_file_references` runs. The record's `file_path` is already an absolute path to the bundled example file, so the existing resolver reads it with no new branch. Pass 2 (`render_template_file` over referenced files and `upstream_access_config`) runs unchanged.

### Piece 3 — Preset functions as Jinja globals (for generated repos only)

`template_populate.py`'s Jinja `Environment` at [template_populate.py:80](src/unitysvc_sellers/template_populate.py:80) gets `register_jinja_globals(env)` so generated repos can author presets natively:

```jinja2
"documents": { "Connectivity test": {{ s3_connectivity_v1() | tojson }} }
```

Generated repos can use either syntax — Jinja call or JSON sentinel — whichever reads better. The SDK never sees a `.j2` listing either way; `update_services.py` has already rendered it to `.json`.

## Why no `{% raw %}`, no scheme, no new resolver branch

Earlier drafts of this ticket introduced a Jinja-rendered listing (`listing.json.j2` read by the SDK) and an `example://` URL scheme for preset file paths. Both were dropped:

- **Jinja-rendered listings** collide with `{{ interface.api_key }}` in `upstream_access_config` and embedded Jinja references, forcing `{% raw %}` everywhere. JSON sentinels sidestep this — Jinja never sees the listing.
- **The `example://` scheme** was defending against scenarios that don't exist in the default flow. Expanded `file_path` values live in memory for milliseconds during upload and are never displayed. Pre-resolving to an absolute path inside the preset function is the simpler, equivalent design.

## Two passes, cleanly separated

| Pass | When | Input | Context | Purpose |
|---|---|---|---|---|
| **1. Preset expansion** | after JSON/TOML parse, before upload | parsed listing dict | preset registry in `unitysvc-sellers-data` | replaces `$preset` nodes with full document records (file_path pre-resolved to absolute path) |
| **2. Referenced-file render** | at upload time | the file at `file_path` (bundled example or local file) | `listing`, `offering`, `provider`, `interface`, `seller`, `local_testing` | substitutes `{{ interface.base_url }}` etc. per listing |

Pass 1 is a pure dict walker — **not** Jinja. Pass 2 is the existing `render_template_file` in [utils.py:213](src/unitysvc_sellers/utils.py:213), untouched. The two passes don't share a namespace; there's nothing to collide.

### 1. The `unitysvc-sellers-data` package

```
unitysvc-sellers-data/
├── pyproject.toml
├── README.md
├── LICENSE
└── src/
    └── unitysvc_sellers_data/
        ├── __init__.py
        ├── _version.py
        ├── presets.py
        └── examples/
            ├── s3-connectivity-v1.sh
            ├── s3-python-boto3-v1.py.j2
            ├── http-connectivity-v1.sh.j2
            └── ...
```

`pyproject.toml`:

```toml
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "unitysvc-sellers-data"
version = "1.0.0"
description = "Standard code examples and presets for unitysvc-sellers"
license = "MIT"
requires-python = ">=3.11"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
unitysvc_sellers_data = ["examples/**/*"]
```

`src/unitysvc_sellers_data/__init__.py`:

```python
from importlib.resources import files as _files
from pathlib import Path

from ._version import __version__
from .presets import PRESETS, expand_preset, register_jinja_globals

__all__ = [
    "__version__",
    "example_path", "read_example", "list_examples",
    "PRESETS", "expand_preset", "register_jinja_globals",
]

_ROOT = _files(__name__).joinpath("examples")


def example_path(name: str) -> Path:
    target = _ROOT.joinpath(name)
    if not target.is_file():
        raise FileNotFoundError(f"Unknown example: {name!r}")
    return Path(str(target))


def read_example(name: str) -> str:
    return example_path(name).read_text(encoding="utf-8")


def list_examples() -> list[str]:
    return sorted(p.name for p in _ROOT.iterdir() if p.is_file())
```

`src/unitysvc_sellers_data/presets.py`:

```python
from copy import deepcopy
from typing import Any

from . import example_path

# File paths are resolved at import time against the installed package,
# so preset records always carry a valid absolute path.

_S3_CONNECTIVITY_V1: dict[str, Any] = {
    "category": "connectivity_test",
    "description": "Verify S3 endpoint is reachable",
    "file_path": str(example_path("s3-connectivity-v1.sh")),
    "is_active": True,
    "is_public": False,
    "meta": {"output_contains": "connectivity ok"},
    "mime_type": "bash",
}

_S3_PYTHON_BOTO3_V1: dict[str, Any] = {
    "category": "usage_example",
    "description": "Python example using boto3",
    "file_path": str(example_path("s3-python-boto3-v1.py.j2")),
    "is_active": True,
    "is_public": True,
    "mime_type": "python",
}

_OVERRIDABLE = frozenset({"description", "is_public", "is_active", "meta"})


def _build(base: dict[str, Any], **overrides: Any) -> dict[str, Any]:
    bad = set(overrides) - _OVERRIDABLE
    if bad:
        raise ValueError(
            f"Cannot override {sorted(bad)!r} on preset {base.get('file_path')!r} "
            f"— these are tied to the file content. Allowed: {sorted(_OVERRIDABLE)!r}"
        )
    out = deepcopy(base)
    for k, v in overrides.items():
        if k == 'meta' and isinstance(v, dict):
            out['meta'] = {**out.get('meta', {}), **v}
        else:
            out[k] = v
    return out


def s3_connectivity_v1(**overrides): return _build(_S3_CONNECTIVITY_V1, **overrides)
def s3_python_boto3_v1(**overrides): return _build(_S3_PYTHON_BOTO3_V1, **overrides)

PRESETS = {
    "s3_connectivity_v1": s3_connectivity_v1,
    "s3_python_boto3_v1": s3_python_boto3_v1,
}


def expand_preset(node: dict[str, Any]) -> dict[str, Any]:
    '''Expand a single {"$preset": ..., "$with": ...} node.'''
    name = node["$preset"]
    overrides = node.get("$with", {}) or {}
    try:
        fn = PRESETS[name]
    except KeyError:
        raise KeyError(f"Unknown preset: {name!r}. Available: {sorted(PRESETS)!r}")
    return fn(**overrides)


def register_jinja_globals(env) -> None:
    '''For generated repos that prefer Jinja call syntax inside .j2 templates.'''
    env.globals.update(PRESETS)
```

### 2. SDK changes — `unitysvc-sellers`

**Dependency** in `pyproject.toml`:

```toml
dependencies = [
  # ...existing...
  "unitysvc-sellers-data>=1.0,<2",
]
```

**Preset expansion walker.** New helper in `src/unitysvc_sellers/upload.py`, called once on the parsed listing dict (and offering dict) before `_resolve_file_references`:

```python
from unitysvc_sellers_data import expand_preset

def _expand_presets(node):
    if isinstance(node, dict):
        if "$preset" in node:
            return expand_preset(node)  # stop recursing — preset record is authoritative
        return {k: _expand_presets(v) for k, v in node.items()}
    if isinstance(node, list):
        return [_expand_presets(v) for v in node]
    return node
```

Wire it into `_build_service_payload` right after `load_data_file` (around [upload.py:242](src/unitysvc_sellers/upload.py:242)). Errors surface immediately with the bad preset name.

**No new branch in `_resolve_file_references`.** Preset expansion has already replaced `file_path` with an absolute path to the bundled file. The existing resolver logic in [upload.py:201](src/unitysvc_sellers/upload.py:201) reads and renders it exactly as it does any other local file. Pass 2's Jinja rendering of the example content happens via `render_template_file` with full per-listing context — unchanged.

**Register Jinja globals in `template_populate.py`** at [template_populate.py:80](src/unitysvc_sellers/template_populate.py:80), strictly for generated repos' convenience:

```python
from unitysvc_sellers_data import register_jinja_globals
register_jinja_globals(env)
```

### 3. New CLI commands

- `usvc data list-presets` — prints preset names + base records.
- `usvc data list-examples` / `usvc data show-example <name>` — browse raw files.

### 4. Docs

- `docs/standard-examples-guide.md` — authoring with `$preset` sentinels, the two-pass model, when to override vs. write custom documents, how to contribute a new preset upstream.
- Getting-started leads with hand-authored JSON + `$preset` (lowest barrier), then mentions the Jinja-call equivalent for generated repos.

## Versioning discipline (load-bearing)

- **Files under `examples/` and preset base dicts are append-only.** `s3-connectivity-v1.sh` and `_S3_CONNECTIVITY_V1` are that content forever. Fixes go into `_V2` plus a new `s3_connectivity_v2` preset name.
- **Sellers upgrade explicitly** by switching `"$preset": "s3_connectivity_v1"` → `"s3_connectivity_v2"`. No implicit migration.
- **Filename and preset-name suffixes carry the version.** Visible in the committed data; `pip upgrade` can't silently change what a seller uploads.
- **Package version:** add a preset → minor bump; never mutate existing `_vN` → no breaking releases in practice. Bump major only to remove a `_vN` (rare).

## Source of truth and authoring

`unitysvc-services-template` remains the human-editable authoring home. Options:

- **A:** `unitysvc-services-template` *is* `unitysvc-sellers-data` — adopt the `src/` layout, `pyproject.toml`, publish from that repo. One repo, one source of truth.
- **B:** CI in `unitysvc-services-template` syncs `examples/` and `presets.py` into a separate `unitysvc-sellers-data` repo and publishes.

Lean toward A unless the template repo has non-package consumers.

## Rejected alternatives

- **Raw URL in `file_path` (GitHub raw).** Long unstable URLs; every upload hits GitHub; needs a custom manifest + cache + checksum layer that reinvents pip badly.
- **Constants bundled inside `unitysvc-sellers`.** Couples template cadence to SDK releases.
- **Runtime `preset://` (or `example://`) URL scheme.** The expanded `file_path` is never user-visible in the default flow; resolving at the preset-function level instead gives us the same behaviour without a custom scheme, a resolver branch, or new documentation.
- **Native `.j2` listing support in the SDK.** Collides with `upstream_access_config` Jinja and with embedded Pass-2 references — forces `{% raw %}` escaping throughout. JSON sentinels handle hand-authored repos without introducing a Pass-1 Jinja layer.

## Open questions

- **Sentinel naming.** `$preset` / `$with` vs. `@preset` / `@with` vs. flattening overrides at top level. Leaning toward explicit `$with` so preset metadata and override payload are visually distinct and schema-validatable.
- **Where to run `_expand_presets`.** Just after parse (cleanest) vs. inside `_resolve_file_references` (fewer call sites). Leaning toward just-after-parse so all preset expansion completes before any file-path resolution.
- **Companion JSON Schema for the sentinel.** Small schema in the data package saying `$preset` must be string, `$with` must be object, no other keys. Cheap, helps IDEs/CI catch typos. Worth doing in v1.
- **Repo shape A vs. B above** — quick call.
- **CI for examples** — shellcheck + `ruff` on rendered output against a fixture listing, run in the package's CI on every PR.

## Scope / next steps

1. Stand up `unitysvc-sellers-data` with empty scaffolding, one preset (`s3_connectivity_v1`) + one file, publish `0.1.0` to PyPI.
2. Land `_expand_presets` walker in `unitysvc-sellers` + `register_jinja_globals` hook into `template_populate.py`.
3. End-to-end tests covering both paths: (a) hand-authored `listing.json` with `$preset` sentinels → upload; (b) generated repo calling `s3_connectivity_v1()` inside `listing.json.j2` → rendered `.json` → upload.
4. Migrate the 15 existing examples into the package with `_v1` suffixes and matching preset functions.
5. Update seller-facing docs; add `usvc data list-presets` / `list-examples` / `show-example`.
6. Update existing seller data repos opportunistically (opt-in, non-breaking — their local `file_path` entries keep working).

**Comment by bo-unitysvc** [comment]
completed
